name: gestion_transmision
description: Starter app de Gestión Transmisión CORAT
publish_to: 'none'
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter_test:
    sdk: flutter

  # Paquetes Firebase compatibles con Flutter 3.35.x
  firebase_core: ^4.2.0
  cloud_firestore: ^6.0.3
  cloud_functions: ^6.0.3
  firebase_auth: ^6.1.1
  firebase_storage: ^13.0.3
  flutter_lints: ^3.0.0
  provider: ^6.0.0
  # Utilidades adicionales
  image_picker: ^1.1.2
  path_provider: ^2.1.4
  intl: ^0.20.2
  lottie: ^3.3.2
  vibration: ^3.1.4
  audioplayers: ^6.5.1
  cupertino_icons: ^1.0.6

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/audio/
    - assets/images/